name: todo
version: 0.1.8
appVersion: 0.1.0
description: Todo is a simple todo application that uses ReactJS for the frontend and kubeless functions for the backend api.
icon: https://www.shareicon.net/download/2016/11/16/854159_pencil_512x512.png
keywords:
- todo
- kubeless
- functions
- react
- redis
home: https://github.com/bitnami-labs/redisdemo
sources:
- https://github.com/bitnami-labs/redisdemo
maintainers:
- name: bitnami-bot
  email: containers@bitnami.com
engine: gotpl
